version: "3"
services:
  master:
    restart: always
    image: eeacms/jenkins-master
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Xmx2048m
      - TZ=America/Costa_Rica
      #- TZ=America/Denver
    volumes:
      - /tmp/jenkins/master_volume/:/var/jenkins_home